# Generated by Django 3.2.9 on 2021-11-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah_buku',
            field=models.IntegerField(null=True),
        ),
    ]
