# Generated by Django 3.2.9 on 2021-11-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211119_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='s',
        ),
    ]
